version: '3.3'
services:

  frontend:
    image: groozzy/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lob/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: groozzy/foodgram_backend
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    env_file:
      - ../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data:
  redoc:
