# Generated by Django 3.2.16 on 2023-12-04 22:01

from django.db import migrations, models
import recipes.enums


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231204_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=recipes.enums.RecipeEnums['TEXT_MAX_LEN'], verbose_name='Описание'),
        ),
    ]
